vich_uploader:
    db_driver: orm

    # mappings:
    #     categories:
    #        uri_prefix: /images/categories
    # #        upload_destination: '%kernel.project_dir%/public/images/products'
    # #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
