---
vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    categories:
      uri_prefix: /images/categories
      upload_destination: "%kernel.project_dir%/public/images/categories"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    # delete_on_update: true
    # delete_on_remove: true

    product:
      uri_prefix: /images/product
      upload_destination: "%kernel.project_dir%/public/images/product"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    # manual:
    #   uri_prefix: /images/product
    #   upload_destination: '%kernel.project_dir%/public/docs/manual'

